-- 0001_model_invocation_log.sql
-- B5 PR1 foundation: REQ-B5-2 model_invocation_log table.
-- This migration is re-runnable on existing lab.db files because it uses
-- CREATE TABLE IF NOT EXISTS / CREATE INDEX IF NOT EXISTS.
--
-- Columns:
--   id              TEXT PRIMARY KEY (randomUUID; generated by the caller)
--   ts              ISO-8601 UTC, defaulted to datetime('now')
--   role            one of IduModelRoleId (CHECK enforces the 13-value list)
--   provider        e.g. opencode-go
--   model           canonical id, e.g. deepseek-v4-pro
--   status          success | failure | skipped
--   prompt_chars    input message length
--   response_chars  output length; 0 on failure
--   error_message   trimmed message, capped at 4 KiB by the repository

CREATE TABLE IF NOT EXISTS model_invocation_log (
  id TEXT PRIMARY KEY,
  ts TEXT NOT NULL DEFAULT (datetime('now')),
  role TEXT NOT NULL CHECK (role IN (
    'supervisor-main',
    'supervisor-semantic',
    'supervisor-compaction',
    'agentlab-general',
    'agentlab-project-understanding',
    'agentlab-security',
    'agentlab-architecture',
    'agentlab-database',
    'agentlab-ui-ux',
    'agentlab-performance',
    'agentlab-code-quality',
    'agentlab-docs',
    'agentlab-librarian'
  )),
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('success','failure','skipped')),
  prompt_chars INTEGER NOT NULL CHECK (prompt_chars >= 0),
  response_chars INTEGER NOT NULL DEFAULT 0 CHECK (response_chars >= 0),
  error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_model_invocation_log_ts
  ON model_invocation_log(ts DESC);

CREATE INDEX IF NOT EXISTS idx_model_invocation_log_role_ts
  ON model_invocation_log(role, ts DESC);
