import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { execFileSync } from "node:child_process";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";

const root = join(import.meta.dirname, "..");
const envPath = join(root, ".env");
const dataDir = join(root, "data");

function parseEnvFile(path) {
	if (!existsSync(path)) return {};
	return Object.fromEntries(
		readFileSync(path, "utf8")
			.split(/\r?\n/u)
			.map((line) => line.trim())
			.filter((line) => line && !line.startsWith("#") && line.includes("="))
			.map((line) => {
				const index = line.indexOf("=");
				return [line.slice(0, index), line.slice(index + 1)];
			}),
	);
}

async function ask(rl, label, defaultValue = "") {
	const suffix = defaultValue ? ` [${defaultValue}]` : "";
	const answer = (await rl.question(`${label}${suffix}: `)).trim();
	return answer || defaultValue;
}

function envSafePath(path) {
	return path.replace(/\\/gu, "/");
}

function detectPiModels(piBin, piCliJs) {
	try {
		const args = piCliJs ? [piCliJs, "--list-models"] : ["--list-models"];
		const outputText = execFileSync(piBin, args, {
			encoding: "utf8",
			stdio: ["ignore", "pipe", "ignore"],
			timeout: 10_000,
		});
		return outputText
			.split(/\r?\n/u)
			.map((line) => line.trim().split(/\s+/u))
			.filter((parts) => parts.length >= 2 && parts[0] !== "provider")
			.map(([provider, model]) => `${provider}/${model}`)
			.slice(0, 40);
	} catch {
		return [];
	}
}

function suggestedProfiles(models) {
	const codex = models.find((model) => model.includes("gpt-5.3-codex"));
	const spark = models.find((model) => model.includes("spark"));
	const parts = ["default|Pi default"];
	if (codex) parts.push(`codex|GPT Codex|--model ${codex}`);
	if (spark) parts.push(`spark|Spark|--model ${spark}`);
	return parts.join(";");
}

const existing = parseEnvFile(envPath);
const defaultHome = homedir();
const defaultPiCli = join(
	homedir(),
	"AppData",
	"Roaming",
	"npm",
	"node_modules",
	"@earendil-works",
	"pi-coding-agent",
	"dist",
	"cli.js",
);

console.log("Pi Telegram Bridge - setup inicial\n");
console.log("Antes de completar esto:");
console.log("1. En Telegram abri @BotFather");
console.log("2. Usa /newbot o /token y copia el TELEGRAM_BOT_TOKEN");
console.log("3. Abri @userinfobot y copia tu numeric user id\n");

const rl = createInterface({ input, output });

try {
	const telegramBotToken = await ask(
		rl,
		"TELEGRAM_BOT_TOKEN",
		existing.TELEGRAM_BOT_TOKEN ?? "",
	);
	const allowedUserId = await ask(
		rl,
		"ALLOWED_USER_ID",
		existing.ALLOWED_USER_ID ?? "",
	);
	const defaultCwd = await ask(
		rl,
		"DEFAULT_CWD",
		existing.DEFAULT_CWD ?? defaultHome,
	);
	const allowedRoots = await ask(
		rl,
		"ALLOWED_ROOTS (; separado)",
		existing.ALLOWED_ROOTS ?? defaultCwd,
	);
	const piBin = await ask(rl, "PI_BIN", existing.PI_BIN ?? "node");
	const piCliJs = await ask(
		rl,
		"PI_CLI_JS",
		existing.PI_CLI_JS ?? defaultPiCli,
	);
	const piExtraArgs = await ask(
		rl,
		"PI_EXTRA_ARGS",
		existing.PI_EXTRA_ARGS ?? "--no-skill-registry --no-lens",
	);
	const detectedModels = detectPiModels(piBin, piCliJs);
	if (detectedModels.length) {
		console.log("\nModelos Pi detectados para usar en PI_AGENT_PROFILES:");
		for (const [index, model] of detectedModels.entries()) {
			console.log(`${index + 1}. ${model}`);
		}
		console.log("");
	}
	const agentProfiles = await ask(
		rl,
		"PI_AGENT_PROFILES",
		existing.PI_AGENT_PROFILES ?? suggestedProfiles(detectedModels),
	);
	const agentWorkspaceRoot = await ask(
		rl,
		"AGENT_WORKSPACE_ROOT",
		existing.AGENT_WORKSPACE_ROOT ??
			join(defaultHome, "Documents", "bridge-agents"),
	);
	const agentWorkspaceMode = await ask(
		rl,
		"AGENT_WORKSPACE_MODE (direct|clone)",
		existing.AGENT_WORKSPACE_MODE ?? "clone",
	);

	if (!telegramBotToken || telegramBotToken.includes("replace_me")) {
		throw new Error("TELEGRAM_BOT_TOKEN es obligatorio.");
	}
	if (!/^\d+$/u.test(allowedUserId)) {
		throw new Error("ALLOWED_USER_ID debe ser numerico.");
	}

	const content = `# Generated by setup-pi-telegram-bridge.bat. Do not commit real secrets.\nTELEGRAM_BOT_TOKEN=${telegramBotToken}\nALLOWED_USER_ID=${allowedUserId}\nDEFAULT_CWD=${envSafePath(defaultCwd)}\nALLOWED_ROOTS=${allowedRoots.split(";").map(envSafePath).join(";")}\nPI_BIN=${piBin}\nPI_CLI_JS=${envSafePath(piCliJs)}\nPI_EXTRA_ARGS=${piExtraArgs}\nPI_AGENT_PROFILES=${agentProfiles}\nAGENT_WORKSPACE_ROOT=${envSafePath(agentWorkspaceRoot)}\nAGENT_WORKSPACE_MODE=${agentWorkspaceMode}\n`;

	writeFileSync(envPath, content, "utf8");
	mkdirSync(dataDir, { recursive: true });

	console.log("\n.env actualizado correctamente.");
	console.log("Proximo paso: ejecuta start-pi-telegram-bridge.bat");
} finally {
	rl.close();
}
