export const QUICK_PROMPT_COMMANDS = ["review", "fix_tests", "audit"];
export const WORK_SESSION_COMMANDS = ["trabajos", "work"];
export const PATH_SESSION_COMMANDS = ["cwd", "new"];
export const LEGACY_SESSION_COMMANDS = ["sessions", "use", "approve", "reject"];

export const PUBLIC_TELEGRAM_HANDLER_COMMANDS = [
	"help",
	"comandos",
	"status",
	"dashboard",
	"idu",
	...QUICK_PROMPT_COMMANDS,
	"safe_push",
	"task",
	"server",
	"agents",
	"config",
	"doctor",
	"testlab",
	"testlab1",
	"testlab2",
	"testlab3",
	"gentest_model_lab",
	"triagereports",
	"syncreports",
	"reports",
	"report",
	"projects",
	"where",
	"addproject",
	"useproject",
	...WORK_SESSION_COMMANDS,
	"ver",
	"nametrabajo",
	"resume",
	"last",
	...PATH_SESSION_COMMANDS,
	"resumen",
	"mem",
	"queue",
	"queue_detail",
	"queue_clear",
	"mode",
	"model",
	"cancel",
	...LEGACY_SESSION_COMMANDS,
] as const;
